### ISSUE TITLE
Unable to import DB

### ISSUE THREAD

**Issue by hkiloco** [Lifeforge-app/lifeforge-api#25]
Unable to import scheme and got the below error:

Failed to import the collections configuration. Raw error:
failed to save collection "idea_box_containers": indexes: (0: Failed to create index idx_o6dotbA - SQL logic error: no such column: name (1)..).

May I know what version of the pocketbase you are using?  
Seems the "schema": [ ] is changed to "fields"

**Comment by melvinchia3636** [comment]
This project is currently under active development, and the db schema is constantly being changed, but I haven't updated the schema json file template in the code base for a while. 

There are still a lot of features and functionalities in the system yet to be implemented and finished, including the documentation is also lacking a lot of contents. 

Unfortunately, I have multiple projects on hand that I have to work on simultaneously, and I'm not able to allocate much time working on this project. 

Hopefully some time next year, when the project is nearly finished, I'll create a docker file and some kind of setup wizard for those who want to use this system to be able to setup everything easily without having to struggle with the configuration.

Appreciate for your interest on the project, and I sincerely apologise for any inconvenience.

**Comment by melvinchia3636** [comment]
I'll make the change log available to the public as soon as possible.

**Comment by melvinchia3636** [comment]
Please refer to [this issue](https://github.com/Lifeforge-app/lifeforge/issues/9)
